const menuData = [
  {
    id: "cat-thali",
    category: "Thali",
    categoryHi: "थाली",
    items: [
      { id: "thali-1", name: "Thali 1", price: 159, unit: "plate", halfPrice: null, desc: "Dal Makhani, Mix Veg, Rice, 2 Roti" },
      { id: "thali-2", name: "Thali 2", price: 209, unit: "plate", halfPrice: null, desc: "Dal Makhani, Paneer, Rice, 2 Roti, Salad" },
      { id: "thali-3", name: "Thali 3", price: 269, unit: "plate", halfPrice: null, desc: "Dal Makhani, Mix Veg, Kadhai Paneer, Rice, Rayta, Salad, Achar, Dessert, Lachha Paratha, Butter Naan" },
    ],
  },
  {
    id: "cat-main-course",
    category: "Main Course",
    categoryHi: "मुख्य भोजन",
    items: [
      { id: "shahi-paneer", name: "Shahi Paneer", price: 250, halfPrice: 160, unit: "plate" },
      { id: "kadhai-paneer", name: "Kadhai Paneer", price: 280, halfPrice: 170, unit: "plate" },
      { id: "paneer-butter-masala", name: "Paneer Butter Masala", price: 270, unit: "plate", halfPrice: null },
      { id: "paneer-lababdar", name: "Paneer Lababdar", price: 270, unit: "plate", halfPrice: null },
      { id: "paneer-do-pyaaza", name: "Paneer Do Pyaaza", price: 270, unit: "plate", halfPrice: null },
      { id: "paneer-tikka-butter-masala", name: "Paneer Tikka Butter Masala", price: 300, unit: "plate", halfPrice: null },
      { id: "paneer-bhurji", name: "Paneer Bhurji", price: 300, unit: "plate", halfPrice: null },
      { id: "palak-paneer", name: "Palak Paneer", price: 270, unit: "plate", halfPrice: null },
      { id: "matar-paneer", name: "Matar Paneer", price: 270, unit: "plate", halfPrice: null },
      { id: "paneer-methi-malai", name: "Paneer Methi Malai", price: 270, unit: "plate", halfPrice: null },
      { id: "gravy-chaap", name: "Gravy Chaap", price: 250, unit: "plate", halfPrice: null },
      { id: "mushroom-matar", name: "Mushroom Matar", price: 270, unit: "plate", halfPrice: null },
      { id: "mushroom-masala", name: "Mushroom Masala", price: 250, unit: "plate", halfPrice: null },
      { id: "dal-makhani", name: "Dal Makhani", price: 190, halfPrice: 120, unit: "plate" },
      { id: "peeli-dal", name: "Peeli Dal", price: 170, halfPrice: 110, unit: "plate" },
      { id: "peeli-dal-tadka", name: "Peeli Dal Tadka", price: 180, halfPrice: 120, unit: "plate" },
      { id: "chana-masala", name: "Chana Masala", price: 170, unit: "plate", halfPrice: null },
      { id: "rajma", name: "Rajma", price: 170, unit: "plate", halfPrice: null },
      { id: "jeera-aloo", name: "Jeera Aloo", price: 170, unit: "plate", halfPrice: null },
      { id: "mix-veg", name: "Mix Veg", price: 200, halfPrice: 120, unit: "plate" },
      { id: "aloo-gobhi-masala", name: "Aloo Gobhi Masala", price: 170, unit: "plate", halfPrice: null },
      { id: "malai-kofta", name: "Malai Kofta", price: 240, unit: "plate", halfPrice: null },
      { id: "veg-kofta", name: "Veg Kofta", price: 220, unit: "plate", halfPrice: null },
    ],
  },
  {
    id: "cat-roti-breads",
    category: "Roti / Breads",
    categoryHi: "रोटी / ब्रेड",
    items: [
      { id: "plain-roti", name: "Plain Roti", price: 15, unit: "piece", halfPrice: null },
      { id: "butter-roti", name: "Butter Roti", price: 22, unit: "piece", halfPrice: null },
      { id: "plain-naan", name: "Plain Naan", price: 45, unit: "piece", halfPrice: null },
      { id: "butter-naan", name: "Butter Naan", price: 55, unit: "piece", halfPrice: null },
      { id: "stuff-naan", name: "Stuff Naan", price: 60, unit: "piece", halfPrice: null },
      { id: "missi-roti", name: "Missi Roti", price: 50, unit: "piece", halfPrice: null },
      { id: "lachha-paratha", name: "Lachha Paratha", price: 50, unit: "piece", halfPrice: null },
      { id: "onion-naan", name: "Onion Naan", price: 60, unit: "piece", halfPrice: null },
      { id: "garlic-naan", name: "Garlic Naan", price: 70, unit: "piece", halfPrice: null },
      { id: "dhaniya-pyaaz-naan", name: "Dhaniya Pyaaz Naan", price: 60, unit: "piece", halfPrice: null },
      { id: "dhaniya-pyaaz-roti", name: "Dhaniya Pyaaz Roti", price: 35, unit: "piece", halfPrice: null },
    ],
  },
  {
    id: "cat-parantha",
    category: "Parantha",
    categoryHi: "परांठा",
    items: [
      { id: "aloo-parantha", name: "Aloo Parantha", price: 80, unit: "piece", halfPrice: null },
      { id: "paneer-parantha", name: "Paneer Parantha", price: 95, unit: "piece", halfPrice: null },
      { id: "pyaaz-parantha", name: "Pyaaz Parantha", price: 85, unit: "piece", halfPrice: null },
      { id: "mix-parantha", name: "Mix Parantha", price: 95, unit: "piece", halfPrice: null },
      { id: "gobhi-parantha", name: "Gobhi Parantha", price: 85, unit: "piece", halfPrice: null },
      { id: "mooli-parantha", name: "Mooli Parantha", price: 85, unit: "piece", halfPrice: null },
      { id: "aloo-pyaaz-parantha", name: "Aloo Pyaaz Parantha", price: 85, unit: "piece", halfPrice: null },
    ],
  },
  {
    id: "cat-rice",
    category: "Rice",
    categoryHi: "चावल",
    items: [
      { id: "jeera-rice", name: "Jeera Rice", price: 170, unit: "plate", halfPrice: null },
      { id: "plain-rice", name: "Plain Rice", price: 140, unit: "plate", halfPrice: null },
      { id: "veg-pulao", name: "Veg Pulao", price: 180, unit: "plate", halfPrice: null },
      { id: "veg-biryani", name: "Veg Biryani Dahi Ke Saath", price: 280, unit: "plate", halfPrice: null },
      { id: "hyderabadi-biryani", name: "Hyderabadi Biryani Dahi Ke Saath", price: 300, unit: "plate", halfPrice: null },
      { id: "rajma-chawal-combo", name: "Rajma Chawal Combo", price: 100, unit: "plate", halfPrice: null },
      { id: "chhole-chawal-combo", name: "Chhole Chawal Combo", price: 100, unit: "plate", halfPrice: null },
    ],
  },
  {
    id: "cat-rayta-salad",
    category: "Rayta, Salad",
    categoryHi: "रायता, सलाद",
    items: [
      { id: "plain-dahi", name: "Plain Dahi", price: 80, unit: "bowl", halfPrice: null },
      { id: "boondi-rayta", name: "Boondi Rayta", price: 100, unit: "bowl", halfPrice: null },
      { id: "mix-rayta", name: "Mix Rayta", price: 110, unit: "bowl", halfPrice: null },
      { id: "pineapple-rayta", name: "Pineapple Rayta", price: 150, unit: "bowl", halfPrice: null },
      { id: "green-salad", name: "Green Salad", price: 100, unit: "plate", halfPrice: null },
      { id: "plain-salad", name: "Plain Salad", price: 25, unit: "plate", halfPrice: null },
    ],
  },
  {
    id: "cat-dips",
    category: "Dips",
    categoryHi: "डिप्स",
    items: [
      { id: "sirka-pyaaz", name: "Sirka Pyaaz", price: 20, unit: "piece", halfPrice: null },
      { id: "pudina-chatni", name: "Pudina Chatni", price: 20, unit: "piece", halfPrice: null },
    ],
  },
  {
    id: "cat-indian-snacks",
    category: "Indian Snacks",
    categoryHi: "इंडियन स्नैक्स",
    items: [
      { id: "samosa", name: "Samosa", price: 18, unit: "piece", halfPrice: null },
      { id: "daal-kachauri", name: "Daal Kachauri", price: 25, unit: "piece", halfPrice: null },
      { id: "aloo-pyaaz-kachauri", name: "Aloo Pyaaz Kachauri", price: 30, unit: "piece", halfPrice: null },
      { id: "chhole-samosa", name: "Chhole Samosa", price: 50, unit: "piece", halfPrice: null },
      { id: "chhole-kachauri", name: "Chhole Kachauri", price: 50, unit: "piece", halfPrice: null },
      { id: "bread-pakoda", name: "Bread Pakoda", price: 25, unit: "piece", halfPrice: null },
      { id: "paneer-bread-pakoda", name: "Paneer Bread Pakoda", price: 35, unit: "piece", halfPrice: null },
      { id: "chhole-bhature", name: "Chhole Bhature", price: 80, unit: "plate", halfPrice: null },
      { id: "mix-pakoda", name: "Mix Pakoda", price: 360, unit: "kg", halfPrice: null },
      { id: "paneer-pakoda", name: "Paneer Pakoda", price: 460, unit: "kg", halfPrice: null },
      { id: "dhokla", name: "Dhokla", price: 240, unit: "kg", halfPrice: null },
      { id: "pav-bhaji", name: "Pav Bhaji", price: 120, unit: "plate", halfPrice: null },
      { id: "extra-pav", name: "Extra Pav", price: 25, unit: "piece", halfPrice: null },
    ],
  },
  {
    id: "cat-chunky-chaat",
    category: "Chunky Chaat",
    categoryHi: "चंकी चाट",
    items: [
      { id: "golgappe", name: "Golgappe (5 Pcs)", price: 30, unit: "plate", halfPrice: null },
      { id: "bharwa-golgappa", name: "Bharwa Golgappa (5 Pcs)", price: 70, unit: "plate", halfPrice: null },
      { id: "dahi-golgappe", name: "Dahi Golgappe (5 Pcs)", price: 80, unit: "plate", halfPrice: null },
      { id: "papdi-chaat", name: "Papdi Chaat", price: 80, halfPrice: 50, unit: "plate" },
      { id: "tikki-chaat", name: "Tikki Chaat", price: 80, halfPrice: 50, unit: "plate" },
      { id: "spe-dahi-bhalle", name: "Spe. Dahi Bhalle", price: 80, halfPrice: 50, unit: "plate" },
      { id: "chhole-tikki", name: "Chhole Tikki", price: 80, halfPrice: 50, unit: "plate" },
      { id: "bread-tikki", name: "Bread Tikki", price: 50, unit: "piece", halfPrice: null },
      { id: "raj-kachauri", name: "Raj Kachauri", price: 120, unit: "piece", halfPrice: null },
    ],
  },
  {
    id: "cat-chaap-tikka",
    category: "Chaap & Tikka",
    categoryHi: "चाप और टिक्का",
    items: [
      { id: "malai-chaap", name: "Malai Chaap", price: 220, halfPrice: 130, unit: "plate" },
      { id: "tandoori-chaap", name: "Tandoori Chaap", price: 210, halfPrice: 125, unit: "plate" },
      { id: "achari-chaap", name: "Achari Chaap", price: 210, halfPrice: 130, unit: "plate" },
      { id: "paneer-tikka", name: "Paneer Tikka", price: 260, halfPrice: 160, unit: "plate" },
      { id: "malai-paneer-tikka", name: "Malai Paneer Tikka", price: 270, halfPrice: 180, unit: "plate" },
      { id: "achari-paneer-tikka", name: "Achari Paneer Tikka", price: 270, halfPrice: 180, unit: "plate" },
      { id: "mushroom-tikka", name: "Mushroom Tikka", price: 250, halfPrice: 160, unit: "plate" },
      { id: "malai-mushroom-tikka", name: "Malai Mushroom Tikka", price: 270, halfPrice: 180, unit: "plate" },
    ],
  },
  {
    id: "cat-burger-sandwich",
    category: "Burger & Sandwich",
    categoryHi: "बर्गर और सैंडविच",
    items: [
      { id: "veg-burger", name: "Veg Burger", price: 60, unit: "piece", halfPrice: null },
      { id: "cheese-burger", name: "Cheese Burger", price: 80, unit: "piece", halfPrice: null },
      { id: "sandwich", name: "Sandwich", price: 30, unit: "piece", halfPrice: null },
      { id: "grill-sandwich", name: "Grill Sandwich", price: 120, unit: "piece", halfPrice: null },
      { id: "cheese-grill-sandwich", name: "Cheese Grill Sandwich", price: 140, unit: "piece", halfPrice: null },
    ],
  },
  {
    id: "cat-pizza",
    category: "Pizza",
    categoryHi: "पिज़्ज़ा",
    items: [
      { id: "cheese-pizza", name: "Cheese Pizza", price: 149, unit: "piece", halfPrice: null },
      { id: "onion-pizza", name: "Onion Pizza", price: 149, unit: "piece", halfPrice: null },
      { id: "capsicum-pizza", name: "Capsicum Pizza", price: 149, unit: "piece", halfPrice: null },
      { id: "tomato-pizza", name: "Tomato Pizza", price: 149, unit: "piece", halfPrice: null },
      { id: "sweet-corn-pizza", name: "Sweet Corn Pizza", price: 149, unit: "piece", halfPrice: null },
      { id: "onion-capsicum-pizza", name: "Onion Capsicum Pizza", price: 159, unit: "piece", halfPrice: null },
      { id: "mushroom-pizza", name: "Mushroom Pizza", price: 189, unit: "piece", halfPrice: null },
      { id: "paneer-pizza", name: "Paneer Pizza", price: 219, unit: "piece", halfPrice: null },
      { id: "mix-deluxe-pizza", name: "Mix Deluxe Pizza", price: 219, unit: "piece", halfPrice: null },
    ],
  },
  {
    id: "cat-pasta",
    category: "Pasta",
    categoryHi: "पास्ता",
    items: [
      { id: "red-sauce-pasta", name: "Red Sauce Pasta", price: 179, unit: "plate", halfPrice: null },
      { id: "white-sauce-pasta", name: "White Sauce Pasta", price: 179, unit: "plate", halfPrice: null },
      { id: "tandoori-sauce-pasta", name: "Tandoori Sauce Pasta", price: 199, unit: "plate", halfPrice: null },
      { id: "mix-sauce-pasta", name: "Mix Sauce Pasta", price: 199, unit: "plate", halfPrice: null },
    ],
  },
  {
    id: "cat-momos",
    category: "Momos",
    categoryHi: "मोमोज़",
    items: [
      { id: "veg-momos-fry", name: "Veg Momos Fry", price: 90, unit: "piece6", halfPrice: null },
      { id: "veg-momos-steam", name: "Veg Momos Steam", price: 90, unit: "piece6", halfPrice: null },
      { id: "paneer-momos-fry", name: "Paneer Momos Fry", price: 110, unit: "piece6", halfPrice: null },
      { id: "paneer-momos-steam", name: "Paneer Momos Steam", price: 110, unit: "piece6", halfPrice: null },
    ],
  },
  {
    id: "cat-chinese",
    category: "Chinese",
    categoryHi: "चाइनीज़",
    items: [
      { id: "veg-chowmein", name: "Veg Chowmein", price: 120, halfPrice: 70, unit: "plate" },
      { id: "singapuri-chowmein", name: "Singapuri Chowmein", price: 170, halfPrice: 100, unit: "plate" },
      { id: "hakka-chowmein", name: "Hakka Chowmein", price: 180, halfPrice: 110, unit: "plate" },
      { id: "paneer-chowmein", name: "Paneer Chowmein", price: 170, halfPrice: 100, unit: "plate" },
      { id: "chili-garlic-chowmein", name: "Chili Garlic Chowmein", price: 140, halfPrice: 80, unit: "plate" },
      { id: "spring-roll", name: "Spring Roll", price: 110, unit: "plate", halfPrice: null },
      { id: "cheese-chili", name: "Cheese Chili (Dry/Gravy)", price: 200, halfPrice: 140, unit: "plate" },
      { id: "manchurian", name: "Manchurian (Dry/Gravy)", price: 170, halfPrice: 100, unit: "plate" },
      { id: "french-fries", name: "French Fries", price: 100, unit: "plate", halfPrice: null },
      { id: "honey-chili-potato", name: "Honey Chili Potato", price: 140, unit: "plate", halfPrice: null },
      { id: "chili-potato", name: "Chili Potato", price: 130, unit: "plate", halfPrice: null },
      { id: "fried-rice", name: "Fried Rice", price: 130, unit: "plate", halfPrice: null },
    ],
  },
  {
    id: "cat-south-indian",
    category: "South Indian",
    categoryHi: "साउथ इंडियन",
    items: [
      { id: "plain-dosa", name: "Plain Dosa", price: 120, unit: "plate", halfPrice: null },
      { id: "rava-plain-dosa", name: "Rava Plain Dosa", price: 150, unit: "plate", halfPrice: null },
      { id: "butter-plain-dosa", name: "Butter Plain Dosa", price: 140, unit: "plate", halfPrice: null },
      { id: "masala-dosa", name: "Masala Dosa", price: 140, unit: "plate", halfPrice: null },
      { id: "butter-masala-dosa", name: "Butter Masala Dosa", price: 160, unit: "plate", halfPrice: null },
      { id: "rava-masala-dosa", name: "Rava Masala Dosa", price: 170, unit: "plate", halfPrice: null },
      { id: "paneer-dosa", name: "Paneer Dosa", price: 180, unit: "plate", halfPrice: null },
      { id: "butter-paneer-dosa", name: "Butter Paneer Dosa", price: 200, unit: "plate", halfPrice: null },
      { id: "rava-paneer-dosa", name: "Rava Paneer Dosa", price: 210, unit: "plate", halfPrice: null },
      { id: "onion-dosa", name: "Onion Dosa", price: 140, unit: "plate", halfPrice: null },
      { id: "onion-masala-dosa", name: "Onion Masala Dosa", price: 150, unit: "plate", halfPrice: null },
      { id: "butter-onion-dosa", name: "Butter Onion Dosa", price: 170, unit: "plate", halfPrice: null },
      { id: "rava-onion-dosa", name: "Rava Onion Dosa", price: 180, unit: "plate", halfPrice: null },
      { id: "tomato-uttapam", name: "Tomato Uttapam", price: 150, unit: "plate", halfPrice: null },
      { id: "onion-uttapam", name: "Onion Uttapam", price: 170, unit: "plate", halfPrice: null },
      { id: "paneer-uttapam", name: "Paneer Uttapam", price: 200, unit: "plate", halfPrice: null },
      { id: "mix-veg-uttapam", name: "Mix Veg Uttapam", price: 170, unit: "plate", halfPrice: null },
    ],
  },
  {
    id: "cat-shake",
    category: "Shake",
    categoryHi: "शेक",
    items: [
      { id: "banana-shake", name: "Banana Shake", price: 100, halfPrice: 80, unit: "glass" },
      { id: "mango-shake", name: "Mango Shake", price: 100, halfPrice: 80, unit: "glass" },
      { id: "chiku-shake", name: "Chiku Shake", price: 150, halfPrice: 120, unit: "glass" },
      { id: "kitkat-shake", name: "Kitkat Shake", price: 80, unit: "glass", halfPrice: null },
      { id: "butter-scotch-oreo", name: "Butter Scotch Oreo Shake", price: 120, unit: "glass", halfPrice: null },
      { id: "butterscotch-shake", name: "Butterscotch Shake", price: 100, unit: "glass", halfPrice: null },
      { id: "classic-cold-coffee", name: "Classic Cold Coffee", price: 100, unit: "glass", halfPrice: null },
      { id: "chocolate-shake", name: "Chocolate Shake", price: 80, unit: "glass", halfPrice: null },
      { id: "classic-vanilla", name: "Classic Vanilla Shake", price: 110, unit: "glass", halfPrice: null },
      { id: "strawberry-shake", name: "Strawberry Shake", price: 120, unit: "glass", halfPrice: null },
    ],
  },
  {
    id: "cat-lassi",
    category: "Lassi",
    categoryHi: "लस्सी",
    items: [
      { id: "sweet-lassi", name: "Sweet Lassi", price: 80, unit: "glass", halfPrice: null },
      { id: "masala-lassi", name: "Masala Lassi", price: 80, unit: "glass", halfPrice: null },
    ],
  },
  {
    id: "cat-soda",
    category: "Soda",
    categoryHi: "सोडा",
    items: [
      { id: "watermelon-mojito", name: "Watermelon Mojito", price: 120, unit: "glass", halfPrice: null },
      { id: "apple-soda", name: "Apple Soda", price: 100, unit: "glass", halfPrice: null },
      { id: "masala-coke", name: "Masala Coke", price: 80, unit: "glass", halfPrice: null },
      { id: "shikanji-masala", name: "Shikanji Masala", price: 60, unit: "glass", halfPrice: null },
      { id: "masala-soda", name: "Masala Soda", price: 60, unit: "glass", halfPrice: null },
      { id: "virgin-mojito", name: "Virgin Mojito", price: 100, unit: "glass", halfPrice: null },
      { id: "pineapple-mojito", name: "Pineapple Mojito", price: 120, unit: "glass", halfPrice: null },
    ],
  },
  {
    id: "cat-juice",
    category: "Juice",
    categoryHi: "जूस",
    items: [
      { id: "anar-juice", name: "Anar Juice", price: 140, halfPrice: 90, unit: "glass" },
      { id: "mosambi-juice", name: "Mosambi Juice", price: 90, halfPrice: 70, unit: "glass" },
      { id: "mix-juice", name: "Mix Juice", price: 90, halfPrice: 70, unit: "glass" },
      { id: "orange-juice", name: "Orange Juice", price: 100, halfPrice: 80, unit: "glass" },
      { id: "pineapple-juice", name: "Pineapple Juice", price: 100, halfPrice: 80, unit: "glass" },
    ],
  },
  {
    id: "cat-desserts",
    category: "Desserts",
    categoryHi: "मिठाई",
    items: [
      { id: "garm-gulabjamun", name: "Garm Gulabjamun", price: 25, unit: "piece", halfPrice: null },
      { id: "spunch-rasgulla", name: "Spunch Rasgulla", price: 25, unit: "piece", halfPrice: null },
      { id: "rajbhog", name: "Rajbhog", price: 35, unit: "piece", halfPrice: null },
      { id: "ras-malai", name: "Ras Malai", price: 50, unit: "piece", halfPrice: null },
      { id: "rabdi-cup", name: "Rabdi Cup", price: 70, unit: "piece", halfPrice: null },
      { id: "garm-jalebi", name: "Garm Jalebi (Desi Ghee)", price: 540, unit: "kg", halfPrice: null },
      { id: "ice-cream", name: "Ice Cream", price: 0, unit: "mrp", halfPrice: null },
    ],
  },
  {
    id: "cat-drinks",
    category: "Drinks",
    categoryHi: "पेय पदार्थ",
    items: [
      { id: "chai", name: "Chai", price: 20, unit: "cup", halfPrice: null },
      { id: "kulhad-chai", name: "Kulhad Chai", price: 30, unit: "cup", halfPrice: null },
      { id: "coffee", name: "Coffee", price: 40, unit: "cup", halfPrice: null },
      { id: "cold-drinks", name: "Cold Drinks", price: 0, unit: "mrp", halfPrice: null },
      { id: "mineral-water", name: "Mineral Water", price: 0, unit: "mrp", halfPrice: null },
    ],
  },
];

export default menuData;
